
var tl1 = gsap.timeline();
var tl2 = gsap.timeline();
var tl3 = gsap.timeline();


tl1.to(".logo",{duration: 3.2, y: 200, ease: "elastic"})
.to(".logo",{duration: 0.5, opacity: 0})
.to(".text-black",{duration: 1.1, opacity: 1,x: 700, ease: "slow"})
.to(".text-black",{duration: 0.5, delay:1,opacity: 0,x: 1000, ease: "rough"})
.to(".text-biszu",{duration: 1.1, opacity: 1,x: 600, ease: "slow"})
.to(".text-biszu",{duration: 0.5, delay:1,opacity: 0,x: 1000, ease: "rough"})
.to(".text-super",{duration: 1.1, opacity: 1,y: 175, ease: "slow"})
.to(".text-super",{duration: 0.5, delay:3.1,opacity: 0,y: 350, ease: "rough"})
.to(".circle",{duration: 0.5, opacity: 0})
.to(".image1",{duration: 1, delay:1, opacity: 1, y: 70, ease: "rough"})
.to('h1', {scale: 0.6, duration: 0.3})
.to('h1', {scale: 1, duration: 0.3})
.to('h1', {scale: 0.7, duration: 0.3})
.to('h1', {scale: 1, duration: 0.3})
.to('h1', {scale: 0.7, duration: 0.3})
.to('h1', {scale: 1, duration: 0.3})
.to("#link1",{opacity: 1})
.to("#link2",{opacity: 1})
.to("#link3",{opacity: 1})
.to(".image1",{duration: 1, delay:3, opacity: 0, y: 150, ease: "slow"})
.to(".image4",{duration: 1, delay:1,opacity: 1, y: 70, ease: "slow"})
.to('h1', {scale: 0.5, duration: 0.3})
.to('h1', {scale: 0.9, duration: 0.3})
.to('h1', {scale: 0.6, duration: 0.3})
.to('h1', {scale: 0.9, duration: 0.3})
.to('h1', {scale: 0.6, duration: 0.3})
.to('h1', {scale: 0.9, duration: 0.3})
.to("#link4",{opacity: 1})
.to("#link5",{opacity: 1})
.to("#link6",{opacity: 1})
.to(".image4",{duration: 1, delay: 3.2,opacity: 0, y: -70, ease: "slow"})
.to(".circle",{duration: 0.5, opacity: 1})
.to(".logo",{duration: 1, y: 200, opacity:1 })
.to('#text1', {opacity:1})
.to('#text2', {opacity:1})
.to('#text2', {scale: 0.6, duration: 0.3, opacity:1})
.to('#text2', {scale: 1, duration: 0.3, opacity: 1})
.to('#text2', {scale: 0.7, duration: 0.3, opacity: 1})
.to('#text2', {scale: 1, duration: 0.3, opacity: 1})
.to('#text2', {scale: 0.7, duration: 0.3, opacity: 1})
.to('#text2', {scale: 1, duration: 0.3, opacity: 1})


tl2.to(".text-friday",{duration: 1.1, delay: 3.7, opacity: 1,x: -500, ease: "slow"})
.to(".text-friday",{duration: 0.5, delay: 1,opacity: 0,x: -1000, ease: "slow"})
.to(".text-prozent",{duration: 1.1, delay: 0.1, opacity: 1,x: -290, ease: "slow"})
.to(".text-prozent",{duration: 0.5, delay: 1,opacity: 0,x: -1000, ease: "slow"})
.to(".text-sale",{duration: 1.1, opacity: 1,y: -90, ease: "slow"})
.to(".text-sale",{duration: 0.5, delay: 3,opacity: 0,y: -500, ease: "slow"})
.to(".image2",{duration: 1, delay:1.5,opacity: 1,y: -73, ease: "slow"})
.to(".image2",{duration: 1, delay: 6.3,opacity: 0,y: -70, ease: "slow"})
.to(".image5",{duration: 1, delay:1,opacity: 1,y: -73, ease: "slow"})
.to(".image5",{duration: 1, delay: 6.5, opacity: 0,y: -70, ease: "slow"})

tl3.to(".text-friday",{duration: 1.1, delay: 3.7, opacity: 1,x: -500, ease: "slow"})
.fromTo(".sale",{ x:0, y:200, opacity:0},{x:190,y:200, scale:1 , delay: 4.3, opacity:1, duration:1})
.to('.sale', {scale: 0.6, duration: 0.3})
.to('.sale', {scale: 1.2, duration: 0.3})
.to('.sale', {scale: 0.6, duration: 0.3})
.to('.sale', {scale: 1.2, duration: 0.3})
.to('.sale', {scale: 0.6, duration: 0.3})
.to('.sale', {scale: 1, duration: 0.3})
.to(".sale",{duration: 0.5, opacity: 0, delay: 1, ease: "slow"})
.to(".image3",{duration: 1, delay:1.8, opacity: 1,y: 70, ease: "slow"})
.to(".image3",{duration: 1, delay: 6.2,opacity: 0,y: -70, ease: "slow"})
.to(".image6",{duration: 1, delay: 1,opacity: 1,y: 70, ease: "slow"})
.to(".image6",{duration: 1, delay: 6.5,opacity: 0,y: 150, ease: "slow"})

